Repository kyverno/backstage-policy-reporter-plugin, pull requests merged in 2025-01, with the labels that each got.

#8 ci(publish): setup github action to publish packages
  .github/workflows/ci.yaml
Labels: enhancement

#9 fix(ci): setup .npmrc instead of env variable
  .npmrc
Labels: bug

#10 docs(development): add steps for setup of kind cluster
  DEVELOPMENT.md
  catalog/entities.yaml
  plugins/policy-reporter/dev/index.tsx
Labels: documentation

#14 docs(readme): add seperate readme for each plugin
  README.md
  plugins/policy-reporter-backend/README.md
  plugins/policy-reporter-common/README.md
  plugins/policy-reporter/README.md
Labels: documentation

#15 docs(package): add keywords
  plugins/policy-reporter-backend/package.json
  plugins/policy-reporter-common/package.json
  plugins/policy-reporter/package.json
Labels: documentation
